apiVersion: apps/v1
kind: Deployment
metadata:
        name: kube-hello-app
spec:
        replicas: 2
        selector:
                matchLabels:
                        app: kube-hello-app
        template:
                metadata:
                        labels:
                                app: kube-hello-app
                spec:
                        containers:
                                 - name: kube-hello-app
                                   image: dockerprofile/image-name:tag
                                   ports:
                                           - containerPort: 3001
                                             protocol: TCP
                                   env:
                                           - name: HELLO_PORT
                                             value: "3001"
