apiVersion: v1
kind: Service
metadata:
        name: kube-hello-svc
        namespace: default
spec:
        selector:
                app: kube-hello-app
        ports:
                - port: 80
                  targetPort: 3001
                  protocol: TCP
